import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#9cf2e8",
        outline: "#6e7977",
        "surface-variant": "#d7e4f0",
        "surface-container": "#e2f0fb",
        tertiary: "#0047bf",
        "on-surface": "#101d25",
        "surface-tint": "#006a63",
        error: "#ba1a1a",
        "inverse-primary": "#80d5cb",
        "surface-container-highest": "#d7e4f0",
        "surface-bright": "#f6faff",
        "surface-container-high": "#dceaf6",
        "inverse-surface": "#25323b",
        "secondary-fixed": "#d7e2ff",
        primary: "#005c55",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#34476a",
        "secondary-container": "#bfd2fd",
        "tertiary-fixed": "#dbe1ff",
        "outline-variant": "#bdc9c6",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#80d5cb",
        "surface-container-low": "#eaf5ff",
        "inverse-on-surface": "#e5f2fe",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#00504a",
        "on-primary-container": "#a3faef",
        "surface-dim": "#cedce7",
        "on-tertiary-fixed": "#00174b",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#003ea8",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#00201d",
        "on-background": "#101d25",
        "secondary-fixed-dim": "#b4c7f1",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#e6e9ff",
        "on-secondary-container": "#475a7e",
        "on-tertiary": "#ffffff",
        secondary: "#4c5e83",
        surface: "#f6faff",
        background: "#f6faff",
        "primary-container": "#0f766e",
        "on-surface-variant": "#3e4947",
        "on-secondary-fixed": "#041b3c",
        "tertiary-container": "#1e5fe7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "gutter-normal": "1rem",
        "panel-padding": "1.25rem",
        "space-2xs": "0.125rem",
        "gutter-dense": "0.5rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "space-lg": "1.25rem",
        "space-base": "1rem",
        "space-2xl": "2rem",
        "space-sm": "0.5rem",
        "space-xl": "1.5rem",
      },
      fontFamily: {
        subheading: ["var(--font-inter)", "Inter", "sans-serif"],
        "page-title": ["var(--font-inter)", "Inter", "sans-serif"],
        "metadata-micro": ["var(--font-inter)", "Inter", "sans-serif"],
        "clinical-data-mono": ["var(--font-mono)", "JetBrains Mono", "monospace"],
        "chief-complaint": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-strong": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-default": ["var(--font-inter)", "Inter", "sans-serif"],
        "section-title": ["var(--font-inter)", "Inter", "sans-serif"],
        "clinical-data": ["var(--font-inter)", "Inter", "sans-serif"],
        "chief-complaint-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "table-header": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        subheading: ["16px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "500" }],
        "page-title": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "metadata-micro": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
        "clinical-data-mono": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "500" }],
        "chief-complaint": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-strong": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "600" }],
        "body-default": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "section-title": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "clinical-data": ["13px", { lineHeight: "18px", letterSpacing: "-0.005em", fontWeight: "500" }],
        "chief-complaint-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "table-header": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
